Repository jenkinsci/postgresql-fingerprint-storage-plugin, pull requests merged in 2023-11, with the labels that each got.

#259 Refresh plugin, enable incrementals and CD
  .github/dependabot.yml
  .github/workflows/cd.yaml
  .mvn/extensions.xml
  .mvn/maven.config
  Jenkinsfile
  pom.xml
  src/test/java/io/jenkins/plugins/postgresql/PostgreSQLConnectionTest.java
Labels: dependencies, chore

#260 Update parent POM, update dependencies, test with Java 21.
  pom.xml
  src/main/java/io/jenkins/plugins/postgresql/jettison/JettisonStaxWriter.java
Labels: dependencies, chore

#265 Rename master to main
  .github/release-drafter.yml
  .gitignore
  README.adoc
Labels: documentation

#268 Add Jenkins security scan
  .github/workflows/jenkins-security-scan.yml
Labels: chore

#266 Bump Jenkins core to 2.414.3
  pom.xml
Labels: dependencies, chore

#269 Add warning about alpha state and convert readme to markdown
  README.adoc
  README.md
Labels: documentation

#271 JENKINS-72142 Move dependencies to API plugins
  pom.xml
Labels: dependencies, chore

#275 Add flyway-core api plugin to prepare moving migration files to flyway
  pom.xml
Labels: chore
